name: sampo
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - expat=2.6.4
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.12.7
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - idna==3.10
      - pyparsing==3.2.1
      - rdflib==7.1.3
      - requests==2.32.3
      - sparqlwrapper==2.0.0
      - tqdm==4.67.1
      - urllib3==2.3.0
